This script was generated by crab (version 2.10.5_patch1).
Running /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/condor_exec.exe with 2 positional parameters: 177 1
Today is Mon Oct 20 09:16:00 EDT 2014 - Mon Oct 20 13:16:00 UTC 2014
Job submitted on host compute-0-5.local
Linux compute-0-5.local 2.6.18-274.el5 #1 SMP Thu Jul 21 12:13:11 EDT 2011 x86_64 x86_64 x86_64 GNU/Linux
>>> current directory (RUNTIME_AREA): /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763
>>> current user: uid=3862(cmspool862) gid=324(cms) groups=324(cms)
>>> directory permission set to 0700
>>> umask set to:  u=rwx,g=,o=
>>> stdout stderr permission set to 0704
>>> voms proxy information:
subject   : /C=DE/O=GermanGrid/OU=DESY/CN=Pooja Saxena/CN=2033352022/CN=245732279
issuer    : /C=DE/O=GermanGrid/OU=DESY/CN=Pooja Saxena/CN=2033352022
identity  : /C=DE/O=GermanGrid/OU=DESY/CN=Pooja Saxena/CN=2033352022
type      : RFC compliant proxy
strength  : 1024 bits
path      : /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/x509up_u23320
timeleft  : 23:59:57
key usage : Digital Signature, Key Encipherment, Data Encipherment
=== VO cms extension information ===
VO        : cms
subject   : /C=DE/O=GermanGrid/OU=DESY/CN=Pooja Saxena
issuer    : /DC=ch/DC=cern/OU=computers/CN=voms.cern.ch
attribute : /cms/Role=NULL/Capability=NULL
attribute : /cms/dcms/Role=NULL/Capability=NULL
attribute : /cms/uscms/Role=NULL/Capability=NULL
timeleft  : 191:42:09
uri       : voms.cern.ch:15002
WNHostName=compute-0-5.local
>>> tar --no-same-permissions -xf /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/default.tgz :
Successful untar
>>> Include /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763 in PYTHONPATH:
strip arguments
env var CRAB_UNIQUE_JOB_ID set to: psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f_177_1_Go2
out_files_177
>>> list of expected files on output sandbox
output files: crab_fjr_177.xml CMSSW_177.stdout CMSSW_177.stderr Watchdog_177.log.gz
>>> GridFlavour discovery: 
source OSG GRID setup script
GridFlavour=OSG
>>> SyncSite discovery: 
SyncSite=T3_US_FIU
>>> SyncCE discovery: 
getting SyncCE from OSG_JOB_CONTACT
SyncCE=fiupg.hep.fiu.edu/jobmanager-condor
>>> info for dashboard:
***** Cat /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/jobreport.txt *****
WNHostName=compute-0-5.local
MonitorJobID=177_https://vocms83.cern.ch//141020//160596.176
SyncGridJobId=https://vocms83.cern.ch//141020//160596.176
MonitorID=psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f
GridFlavour=OSG
SyncSite=T3_US_FIU
SyncCE=fiupg.hep.fiu.edu/jobmanager-condor
***** End Cat jobreport *****
Parameters sent to Dashboard.
>>> setup environment
set SCRAM ARCH to slc6_amd64_gcc481
SCRAM_ARCH = slc6_amd64_gcc481
>>> Created working directory: /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490
Change to working directory: /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490
>>> current directory (WORKING_DIR): /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490
>>> setup CMS OSG environment:
set SCRAM ARCH to slc6_amd64_gcc481
SCRAM_ARCH = slc6_amd64_gcc481
OSG_APP is /osg/apps
sourcing /osg/apps/cmssoft/cms/cmsset_default.sh ...
==> setup cms environment ok
SCRAM_ARCH = slc6_amd64_gcc481
>>> specific cmssw setup environment:
CMSSW_VERSION =  CMSSW_7_1_0
WARNING: Developer's area is created for architecture slc6_amd64_gcc481 while your current OS is SLC5.
>>> current directory (SOFTWARE_DIR): /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490/CMSSW_7_1_0
PreserveSeeds: <>
IncrementSeeds:<>
>>> info for dashboard:
***** Cat /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/jobreport.txt *****
MonitorJobID=177_https://vocms83.cern.ch//141020//160596.176
MonitorID=psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f
***** End Cat jobreport *****
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Parameters sent to Dashboard.
crabWatchdog started as process 2608
>>> moving CMSSW software directories in /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490/CMSSW_7_1_0
mv: cannot stat `/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/module/': No such file or directory
>>> Include /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763 in PYTHONPATH:
PYTHONPATH=/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/:/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490/CMSSW_7_1_0/python:/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490/CMSSW_7_1_0/lib/slc6_amd64_gcc481:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/python:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/lib/slc6_amd64_gcc481:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/coral/CORAL_2_3_21-cms20/slc6_amd64_gcc481/python:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/coral/CORAL_2_3_21-cms20/slc6_amd64_gcc481/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/pyqt/4.8.1-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-scipy/0.8.0-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-matplotlib/1.2.1-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/yoda/1.0.4/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python-ldap/2.4.10-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/sip/4.11.2-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/llvm/3.4-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-sqlalchemy/0.8.2-cms2/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-pycurl/7.19.0-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-python-dateutil/1.1-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-numpy/1.6.1-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-lint/0.25.1-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-ipython/0.10-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-cx-oracle/5.1-cms2/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-cjson/1.0.5-cms/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/frontier_client/2.8.10/python/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/das-client/2.5.0/bin:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/cython/0.19.1/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/rivet/1.8.2-cms5/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/pyminuit2/0.0.1-cms14/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-pygithub/1.23.0/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/py2-networkx/1.8.1/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/professor/1.0.0-cms14/lib/python2.7/site-packages:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/lcg/root/5.34.18-cms/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/dbs-client/DBS_2_1_9-cms/lib:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/dbs-client/DBS_2_1_9-cms/lib/DBSAPI:/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/cvs2git/5419-cms/lib:/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/
edmConfigHash: error while loading shared libraries: /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/lib/slc6_amd64_gcc481/libFWCorePythonParameterSet.so: ELF file OS ABI invalid
edmConfigHash: error while loading shared libraries: /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/lib/slc6_amd64_gcc481/libFWCorePythonParameterSet.so: ELF file OS ABI invalid
PSETHASH = 
/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/writeCfg.py pset.py pset.py
 
# LIMITS USED BY CRAB WATCHDOG:
# RSS  (KBytes)   : 2300000
# VSZ  (KBytes)   : 100000000
# DISK (MBytes)   : 19000
# CPU TIME        : 720h:0m:0s
# WALL CLOCK TIME : 21h:50m:0s
 
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Importing .py file
Setting parameters
RandomNumberGeneratorService found, will attempt to change seeds
inputBlocks=
inputFiles=
parentFiles=
lumisRange=
>>> Executable cmsRun
/cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/bin/slc6_amd64_gcc481/cmsRun
ok executable found
>>> info for dashboard:
***** Cat /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/jobreport.txt *****
MonitorJobID=177_https://vocms83.cern.ch//141020//160596.176
MonitorID=psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f
ExeStart=cmsRun
***** End Cat jobreport *****
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Parameters sent to Dashboard.
>>> cmsRun started at Mon Oct 20 13:16:08 UTC 2014
>>> cmsRun ended at Mon Oct 20 13:16:08 UTC 2014
chmod: cannot access `/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/crab_fjr_*.xml': No such file or directory
>>> crab_fjr_*.xml  permission set to 0704
>>> info for dashboard:
***** Cat /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/jobreport.txt *****
MonitorJobID=177_https://vocms83.cern.ch//141020//160596.176
MonitorID=psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f
ExeEnd=cmsRun
***** End Cat jobreport *****
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Parameters sent to Dashboard.
TIME_EXE = 0 sec
>>> cmsRun wrote 1 lines of stdout+stderr
>>> START OF printout of 1 lines from stdout+stderr
cmsRun: error while loading shared libraries: /cvmfs/cms.cern.ch/slc6_amd64_gcc481/cms/cmssw/CMSSW_7_1_0/lib/slc6_amd64_gcc481/libFWCoreFramework.so: ELF file OS ABI invalid
>>> END OF printout of 1 lines from stdout+stderr
>>> Parse FrameworkJobReport crab_fjr.xml
CRAB FrameworkJobReport crab_fjr.xml is not available, using exit code of executable from command line.
>>> Executable failed  127
ExeExitCode=127
EXECUTABLE_EXIT_STATUS = 127
CrabWrapper EXIT_FUNC entered at Mon Oct 20 09:16:09 EDT 2014   -  Mon Oct 20 13:16:09 UTC 2014
Checking output files:  
will tar file crab_fjr_177.xml in  out_files_177
WARNING: output file CMSSW_177.stdout not found!
WARNING: output file CMSSW_177.stderr not found!
WARNING: output file Watchdog_177.log.gz not found!
>>> working dir = /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490
>>> current directory (RUNTIME_AREA): /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763
>>> Remove working directory: /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/cms_baYELnvx2490
>>> padding time: Sleeping the wrapper for 591 seconds
STOPPING WATCHDOG. CrabWatchdog PID is 2608
********** LAST 50 LINES OF WATCHDOG LOG
# RESOURCE USAGE SUMMARY FOR PROCESS ID  2459
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
3862      2459  0.4  0.0  11088  1500 ?        SN   09:16   0:00 /bin/sh /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/condor_exec.exe 177 1
 
# LIMITS USED BY CRAB WATCHDOG:
# RSS  (KBytes)   : 2300000
# VSZ  (KBytes)   : 100000000
# DISK (MBytes)   : 19000
# CPU TIME        : 720h:0m:0s
# WALL CLOCK TIME : 21h:50m:0s
 
# FOLLOWING PRINTOUT TRACKS MAXIMUM VALUES OF RESOURCES USE
# ONE LINE IS PRINTED EACH TIME A MAXIMUM CHANGES
# IF CHANGE WAS IN RSS OR VSZ ALSO PROCID AND COMMAND ARE PRINTED
# THERE IS NO PRINTOUT FOR CPU/WALL TIME INCREASE
 
# TIME			PID	RSS(KB)	VSZ(KB)	Dsk(MB)	tCPU(s)	tWALL(s)	COMMAND
 Oct 20 09:16:05 EDT	2459	1500	11088	0	0	0	/bin/sh /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/condor_exec.exe 177 1       
 Oct 20 09:16:05 EDT	2621	6724	19052	0	0	0	python /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/writeCfg.py pset.py pset.py       
 Oct 20 09:16:05 EDT	18127	7536	94512	0	0	0	/var/opt/condor/execute/dir_12682/glide_M12736/main/condor/sbin/condor_master -f -pidfile /var/opt/condor/execute/dir_12682/glide_M12736/condor_master2.pid       
 Oct 20 09:16:05 EDT	19763	8488	95280	0	0	0	condor_startd -f         
 Oct 20 09:16:05 EDT	---	8488	95280	6	----	----	----
 Oct 20 09:18:05 EDT	19763	8496	95420	6	0	121	condor_startd -f         
********** WATCHDOG LOG ENDED
ZIPPING WATCHDOG LOG
Disk space used:
du -sh /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763
3.6M	/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763
Found unusual stdout, rename for OSB
`/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/_condor_stdout' -> `CMSSW_177.stdout'
Found unusual stderr, rename for OSB
`/var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/_condor_stdout' -> `CMSSW_177.stderr'
crab_fjr_177.xml
CMSSW_177.stdout
CMSSW_177.stderr
Watchdog_177.log.gz
Total Output dimension: 5324
WARNING: output files size limit is set to: 50000000
Total Output dimension 5324 is fine.
JOB_EXIT_STATUS = 127
>>> info for dashboard:
***** Cat /var/opt/condor/execute/dir_12682/glide_M12736/execute/dir_21763/jobreport.txt *****
MonitorJobID=177_https://vocms83.cern.ch//141020//160596.176
MonitorID=psaxena_GEN-SIM-DIGI-L1_v1_010813_i64q1f
ExeTime=0
ExeExitCode=127
CrabUserCpuTime=0.00
CrabSysCpuTime=0.00
CrabCpuPercentage=0%
CrabWrapperTime=600
CrabStageoutTime=NULL
JobExitCode=127
***** End Cat jobreport *****
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc481/external/python/2.7.3-cms/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type %s' % name)
ValueError: unsupported hash type sha512
Parameters sent to Dashboard.
EXITING at Mon Oct 20 09:26:02 EDT 2014  -  Mon Oct 20 13:26:02 UTC 2014
